services:
  # Prometheus
  mopcon-prometheus:
    container_name: mopcon-prometheus
    image: prom/prometheus
    restart: unless-stopped
    networks:
      - mopcon-network
    ports:
      - 9090:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus:/prometheus

    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml

  # Node Exporter
  mopcon-node-exporter:
    image: prom/node-exporter
    container_name: mopcon-node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - mopcon-network
    command:
      - --web.listen-address=:9100

  # Nginx Exporter
  mopcon-nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: mopcon-nginx-exporter
    restart: always
    ports:
      - "9113:9113"
    networks:
      - mopcon-network
    command:
      - --web.listen-address=:9113
      - --nginx.scrape-uri=http://mopcon-nginx:8080/nginx_status

networks:
  mopcon-network:
    external: true
