global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      # Prometheus
      - targets: ['localhost:9090']
        labels:
          instance: MOPCON-PROMETHEUS

  - job_name: exporters
    static_configs:
      # Node Exporter - Local
      - targets: ['mopcon-node-exporter:9100']
        labels:
          instance: MOPCON-NODE-LOCAL

      # Node Exporter - Remote
      - targets: ['152.42.237.237:9100']
        labels:
          instance: MOPCON-NODE-UBUNTU

      # Nginx Exporter
      - targets: ['mopcon-nginx-exporter:9113']
        labels:
          instance: MOPCON-NODE-NGINX
