global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      # Prometheus
      - targets: ['localhost:9090']
        labels:
          instance: MOPCON-PROMETHEUS

  - job_name: exporters
    static_configs:
      # Node Exporter - Local
      - targets: ['mopcon-node-exporter:9100']
        labels:
          instance: MOPCON-NODE-LOCAL
