global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      # Prometheus
      - targets: ['localhost:9090']
        labels:
          instance: MOPCON-PROMETHEUS
